-type headers() :: [{bitstring(), bitstring()}].
-type body() :: bitstring().
-type chb() :: {integer(), headers(), body()}.
-type chb_lookup() :: #{ bitstring() => [chb()]}.
-type forwarder() :: {email, bitstring()}.
-type epstate() :: #{ mappings => chb_lookup(), forwarders => [forwarder()] }.
-type mhb() :: {bitstring(), headers(), bitstring()}.
